services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: tradewiseUser
      POSTGRES_PASSWORD: tradewisePassword
      POSTGRES_DB: tradewise_database
    ports:
      - "15432:5432"
