<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>d3738121-edc0-4b8b-a675-101f6f2d58e7</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <Content Update="appsettings.*.json">
            <DependentUpon>appsettings.json</DependentUpon>
        </Content>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Mapster" Version="7.4.2-pre02"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.3"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="8.0.2"/>
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="7.2.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="7.2.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="7.2.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TradeWiseBackend.Bll\TradeWiseBackend.Bll.csproj"/>
        <ProjectReference Include="..\TradeWiseBackend.Dal\TradeWiseBackend.Dal.csproj"/>
        <ProjectReference Include="..\TradeWiseBackend.Domain\TradeWiseBackend.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
