<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>939909cd-0d50-414b-8db2-703047c56f19</UserSecretsId>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TradeWiseBackend.Domain\TradeWiseBackend.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Mapster" Version="7.4.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.4"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.4"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4"/>
        <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.4"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Repositories\"/>
    </ItemGroup>

</Project>
